version: 3.7"

services:
  db:
    image: postgres:14.0-alpine
    container_name: metrics_evaluation_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5430:5432"
    env_file:
      - "db.env"

volumes:
  postgres_data:
