version: '3.8'
services:
    app:
        container_name: flask_metrics
        image: "flask-metrics"
        ports:
            - "5000:5000"
        command: python3 /app/main.py 0.0.0.0
        env_file:
            - .env
        networks:
            - db_docker_metrics_db

networks:
    db_docker_metrics_db:
        external: true

#networks:
#    default:
#        name: db_docker_metrics_db
#        external: true

